@CloudSync.Api_HostAddress = http://localhost:5028
@Docker_HostAddress = http://localhost:5000

### Data Sync Request (Local)
POST {{CloudSync.Api_HostAddress}}/api/DataSync
Content-Type: application/json

"Sample data to synchronize"

###

### Data Sync Request (Docker)
POST {{Docker_HostAddress}}/api/DataSync
Content-Type: application/json

"Sample data to synchronize"

###

### Health Check Request (Local)
GET {{CloudSync.Api_HostAddress}}/api/HealthCheck/test-connections
Accept: application/json

###

### Health Check Request (Docker)
GET {{Docker_HostAddress}}/api/HealthCheck/test-connections
Accept: application/json

###
