version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__AzureConnection=Server=azure-db;Database=AzureDb;User Id=sa;Password=P@ssw0rd;TrustServerCertificate=True;
      - ConnectionStrings__AwsConnection=Server=aws-db;Database=AwsDb;User Id=sa;Password=P@ssw0rd;TrustServerCertificate=True;
      - ASPNETCORE_URLS=http://+:80
      # Performance optimizations
      - DOTNET_GCServer=1
      - DOTNET_GCConcurrent=1
      - DOTNET_GCRetainVM=1
    depends_on:
      azure-db:
        condition: service_healthy
      aws-db:
        condition: service_healthy
    restart: unless-stopped
    # Resource limits for consistent performance testing
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 4G
        reservations:
          cpus: '2.0'
          memory: 2G
    # Network optimizations
    sysctls:
      net.core.somaxconn: 65535
      net.ipv4.tcp_tw_reuse: 1
      net.ipv4.tcp_fin_timeout: 30
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  perftest:
    build:
      context: .
      dockerfile: Dockerfile.perftest
    environment:
      - API_BASE_URL=http://api:80
      - DOTNET_GCServer=1
      - DOTNET_ThreadPool_UnfairSemaphoreSpinLimit=6
    depends_on:
      api:
        condition: service_healthy
    volumes:
      - ./performance-results:/app/results
    restart: "no" # Don't restart performance tests automatically
    # High resource limits for load generation
    deploy:
      resources:
        limits:
          cpus: '6.0'
          memory: 8G
        reservations:
          cpus: '4.0'
          memory: 4G
    # Network optimizations for high throughput
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    sysctls:
      net.core.somaxconn: 65535
      net.ipv4.ip_local_port_range: "1024 65535"
      net.ipv4.tcp_tw_reuse: 1

  azure-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssw0rd
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    restart: unless-stopped
    # Database performance optimizations
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '1.0'
          memory: 1G
    volumes:
      - azure-db-data:/var/opt/mssql
      - ./Scripts/init-azure-db.sql:/docker-entrypoint-initdb.d/init-azure-db.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P P@ssw0rd -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  aws-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssw0rd
      - MSSQL_PID=Developer
    ports:
      - "1434:1433"
    restart: unless-stopped
    # Database performance optimizations
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '1.0'
          memory: 1G
    volumes:
      - aws-db-data:/var/opt/mssql
      - ./Scripts/init-aws-db.sql:/docker-entrypoint-initdb.d/init-aws-db.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P P@ssw0rd -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Database initializer service
  db-init:
    image: mcr.microsoft.com/mssql/server:2022-latest
    depends_on:
      azure-db:
        condition: service_healthy
      aws-db:
        condition: service_healthy
    volumes:
      - ./Scripts:/scripts:ro
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssw0rd
    command: >
      bash -c "
        echo 'Waiting for databases to be ready...' &&
        sleep 10 &&
        echo 'Initializing Azure database...' &&
        /opt/mssql-tools/bin/sqlcmd -S azure-db -U sa -P P@ssw0rd -i /scripts/init-azure-db.sql &&
        echo 'Initializing AWS database...' &&
        /opt/mssql-tools/bin/sqlcmd -S aws-db -U sa -P P@ssw0rd -i /scripts/init-aws-db.sql &&
        echo 'Database initialization completed successfully!'
      "
    restart: "no"

  # Optional monitoring service for performance insights
  monitoring:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    profiles:
      - monitoring

volumes:
  azure-db-data:
  aws-db-data:
  prometheus-data:

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1500